Fixes Button on hover
warmachine028/nike pull request #185
Opened 2023-10-24 02:45 UTC by KriteshTimsina

# Issue fixed #184  📐

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #<issuenumber>

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

<attach screenshots here>
  
  
  
---

2023-10-24 16:37 UTC, warmachine028 commented
- change PR title.
- Use the PR template properly. 
- see closed PRs

2023-10-26 20:09 UTC, warmachine028 requested changes
Make the changes in PR template and title

2023-10-27 01:17 UTC, KriteshTimsina commented
Check now

2023-10-27 10:12 UTC, warmachine028 approved these changes

2023-10-27 10:13 UTC, merged